name: container-image
run-name: Container Image CI

on:
  push:
    branches: [ "main", "develop"]
  pull_request:
    branches: [ "main", "develop"]

env:
  registry_username: ${{ vars.REGISTRY_USERNAME }}
  registry_password: ${{ secrets.REGISTRY_PASSWORD }}
  registry_host: ${{ vars.REGISTRY_HOST }}
  container_id: $(date +%s)
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v1'
      with:
        username: ${{ env.registry_username }}
        password: ${{ env.registry_password }}
        registry: ${{ env.registry_host }}

    - name: Set container id
      id: container_id
      run: echo "::set-output name=ID::${{ env.container_id }}"

    - name: Build the container image
      run: |
        
        docker build --tag ${{ env.registry_host }}/${{ env.registry_username }}/desafio-stn:${{ steps.container_id.outputs.ID }}  -f ./src/build/Dockerfile .
      working-directory: ./

    - name: Publish the image
      run: |
        docker push ${{ env.registry_host }}/${{ env.registry_username }}/desafio-stn:${{ steps.container_id.outputs.ID }}
      working-directory: ./
