name: container-image
run-name: Container Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  name: ${{ github.ref_name }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build --tag tomelin/desafio-stn:$(date +%s) -f ./src/build/Dockerfile .
      # working-directory: ./
    - name: GITHUB_HEAD_REF
      run: echo "${GITHUB_HEAD_REF}"
    - name: GITHUB_REF_NAME
      if:  github.ref_name == 'main'
      run: echo "${GITHUB_REF_NAME}"
    - name: ref_name
      if:  github.ref_name == 'main'
      run: echo  ${{ github.ref_name }}
     