name: deployment-kubernetes
run-name: Deployment resources in Kubernetes CI

on:
  workflow_call:
    inputs:
      kube-config:
        required: true
        type: string
      environment:
        required: true
        type: string  
env:
  kube_production: kttps://production-kubernetes.default.svc:443
  kube_development: kttps://development-kubernetes.default.svc:443

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy in production
      if: inputs.environment == 'production'
      run: |
        echo "deploy ArgoCD manisfests in production: ${{ env.kube_production }}"
    
    - name: Deploy in development
      if: inputs.environment == 'development'
      run: |
        echo "deploy ArgoCD manisfests in development: ${{ env.kube_development }}"