name: deploy
run-name: Deploy

on:
  workflow_call:
    inputs:
      kube-config:
        required: true
        type: string

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
          kube-config: ${{ inputs.kube-config }}

    - name: output kubeconfig
      run: |
        echo ${{ inputs.kube-config }} > /tmp/config.txt
        cat /tmp/config.txt
        rm -f /tmp/config.txt

    - name: event inputs kubeconfig
      run: |
        echo ${{ github.event.inputs.kube-config }} > /tmp/config.txt
        cat /tmp/config.txt
        rm -f /tmp/config.txt
      