name: deployment-kubernetes
run-name: Deployment resources in Kubernetes CI

on:
  workflow_call:
    inputs:
      kube-config:
        required: true
        type: string
      environment:
        required: true
        type: string  
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy in production
      if: inputs.environment == 'https://cluster-production:443'
      run: |
        echo "deploy ArgoCD manisfests in production: ${{ github.event.inputs.kube-config }}"
    
    - name: Deploy in development
      if: inputs.environment == 'https://cluster-development:443'
      run: |
        echo "deploy ArgoCD manisfests in development: ${{ github.event.inputs.environment }}"