name: deployment-kubernetes
run-name: Deployment resources in Kubernetes CI

on:
  workflow_run:
    workflows: ["terraform-deployment"]
    types:
      - completed

  
env:
  production: "https://internal-sxxx5irz.hcp.eastus.azmk8s.io:443"
  develop: "https://internal-sxxx5irz.hcp.eastus.azmk8s.io:443"

jobs:
  inpus:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash


    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      # - name: event inputs
      #   run: |
      #     echo "${{ github.event.inputs.VAR1 }}"

      - name: event name
        run: |
            echo "${{ github.event.workflow.name }}"
      - name: event action
        run: |
                echo "${{ github.event.action }}"
      - name: event action
        run: |
           echo "${{ github.event_name }}"
      - name: event action
        run: |
              echo "${{ github.event.workflow_run.conclusion }}"
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash


    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1  

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra/terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./infra/terraform
