name: deployment-kubernetes
run-name: Deployment resources in Kubernetes CI

on:
  # workflow_run:
  #   workflows: 
  #     - container.yaml
  #   types:
  #     - completed

  push:
    branches: [ "main", "develop", "production" ]
  pull_request:
    branches: [ "main", "develop", "production" ]
env:
  production: "https://internal-sxxx5irz.hcp.eastus.azmk8s.io:443"
  develop: "https://internal-sxxx5irz.hcp.eastus.azmk8s.io:443"

jobs:

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash


    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1  

    - name: Terraform Init
      run: terraform init
      working-directory: ./infra/terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ./infra/terraform
