name: first

on:
  workflow_run:
    workflows: ["second"]
    types:
      - completed

jobs:

  first:
    name: 'First'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Uptime
      run: uptime
      working-directory: ./infra/terraform