name: second

on:
  push:
    branches: [ "main", "develop", "production"]

jobs:

  second:
    name: 'Second...'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Sleep
      run: sleep 5
      working-directory: ./infra/terraform