name: second

on:
  push:
    branches: [ "main", "develop", "production"]

jobs:

  first:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1  

    - name: Terraform Init
      run: sleep 5
      working-directory: ./infra/terraform